--
-- Скрипт сгенерирован Devart dbForge Studio 2019 for SQL Server, Версия 5.7.99.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/sql/studio
-- Дата скрипта: 31.03.2020 0:48:00
-- Версия сервера: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'AND', N'Andorra', N'flag_andorra.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ARG', N'Argentina', N'flag_argentina.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'AUS', N'Australia', N'flag_australia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'AUT', N'Austria', N'flag_austria.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'BEL', N'Belgium', N'flag_belgium.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'BOT', N'Botswana', N'flag_botswana.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'BRA', N'Brazil', N'flag_brazil.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'BUL', N'Bulgaria', N'flag_bulgaria.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CAF', N'Central African Republic', N'flag_central_african_republic.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CAN', N'Canada', N'flag_canada.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CHI', N'Chile', N'flag_chile.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CHN', N'China', N'flag_china.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CIV', N'Ivory Coast', N'flag_ivory_coast.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CMR', N'Cameroon', N'flag_cameroon.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'COL', N'Colombia', N'flag_colombia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CRO', N'Croatia', N'flag_croatia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'CZE', N'Czech Republic', N'flag_czech_republic.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'DEN', N'Denmark', N'flag_denmark.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'DOM', N'Dominican Republic', N'flag_dominican_republic.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ECU', N'Ecuador', N'flag_ecuador.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'EGY', N'Egypt', N'flag_egypt.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ESA', N'El Salvador', N'flag_el_salvador.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ESP', N'Spain', N'flag_spain.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'EST', N'Estonia', N'flag_estonia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'FIN', N'Finland', N'flag_finland.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'FRA', N'France', N'flag_france.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GBR', N'United Kingdom', N'flag_united_kingdom.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GBS', N'Guinea-Bissau', N'flag_guinea.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GEQ', N'Equatorial Guinea', N'flag_equatorial_guinea.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GER', N'Germany', N'flag_germany.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GRE', N'Greece', N'flag_greece.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GUA', N'Guatemala', N'flag_guatemala.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'GUI', N'Guinea', N'flag_guinea-bissau.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'HKG', N'Hong Kong', N'flag_hong_kong.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'HON', N'Honduras', N'flag_honduras.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'HUN', N'Hungary', N'flag_hungary.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'INA', N'Indonesia', N'flag_indonesia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'IND', N'India', N'flag_india.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'IRL', N'Ireland', N'flag_ireland.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ISR', N'Israel', N'flag_israel.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ITA', N'Italy', N'flag_italy.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'JAM', N'Jamaica', N'flag_jamaica.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'JOR', N'Jordan', N'flag_jordan.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'JPN', N'Japan', N'flag_japan.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'KEN', N'Kenya', N'flag_kenya.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'KOR', N'South Korea', N'flag_south_korea.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'KSA', N'Saudi Arabia', N'flag_saudi_arabia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'LAT', N'Latvia', N'flag_latvia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'LIE', N'Liechtenstein', N'flag_liechtenstein.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'LTU', N'Lithuania', N'flag_lithuania.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'LUX', N'Luxembourg', N'flag_luxembourg.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MAC', N'Macau', N'flag_macau.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MAD', N'Madagascar', N'flag_madagascar.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MAS', N'Malaysia', N'flag_malaysia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MDA', N'Moldova', N'flag_moldova.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MEX', N'Mexico', N'flag_mexico.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MKD', N'Macedonia', N'flag_macedonia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MLI', N'Mali', N'flag_mali.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MLT', N'Malta', N'flag_malta.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MNE', N'Montenegro', N'flag_montenegro.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MON', N'Monaco', N'flag_monaco.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'MRI', N'Mauritius', N'flag_mauritius.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'NCA', N'Nicaragua', N'flag_nicaragua.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'NED', N'Netherlands', N'flag_netherlands.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'NIG', N'Niger', N'flag_niger.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'NOR', N'Norway', N'flag_norway.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'NZL', N'New Zealand', N'flag_new_zealand.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'PAN', N'Panama', N'flag_panama.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'PAR', N'Paraguay', N'flag_paraguay.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'PER', N'Peru', N'flag_peru.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'PHI', N'Philippines', N'flag_philippines.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'POL', N'Poland', N'flag_poland.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'POR', N'Portugal', N'flag_portugal.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'PUR', N'Puerto Rico', N'flag_puerto_rico.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'QAT', N'Qatar', N'flag_qatar.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'ROU', N'Romania', N'flag_romania.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'RSA', N'South Africa', N'flag_south_africa.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'RUS', N'Russia', N'flag_russia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'SEN', N'Senegal', N'flag_senegal.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'SIN', N'Singapore', N'flag_singapore.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'SUI', N'Switzerland', N'flag_switzerland.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'SVK', N'Slovakia', N'flag_slovakia.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'SWE', N'Sweden', N'flag_sweden.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'THA', N'Thailand', N'flag_thailand.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'TPE', N'Chinese Taipei', N'flag_chinese_taipei.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'TUR', N'Turkey', N'flag_turkey.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'UAE', N'United Arab Emirates', N'flag_united_arab_emirates.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'URU', N'Uruguay', N'flag_uruguay.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'USA', N'United States', N'flag_usa.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'VAT', N'Vatican', N'flag_vatican.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'VEN', N'Venezuela', N'flag_venezuela.png')
INSERT [marathon-se].dbo.Country(CountryCode, CountryName, CountryFlag) VALUES (N'VIE', N'Vietnam', N'flag_vietnam.png')
GO